# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-09 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gramygram', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='thegram/')),
                ('caption', models.CharField(max_length=100)),
            ],
        ),
    ]
