# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-12 02:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gramygram', '0004_auto_20180309_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='image_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
