# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-12 06:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gramygram', '0005_image_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200)),
                ('time_comment', models.DateTimeField(auto_now_add=True, null=True)),
                ('image_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gramygram.Image')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gramygram.User')),
            ],
            options={
                'ordering': ['-time_comment'],
            },
        ),
    ]
