# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-15 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gramygram', '0003_auto_20180315_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='username',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
